// [TASK: ATOM-INFRA-506]
import * as cdk from 'aws-cdk-lib';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

/**
 * All application credentials as AWS Secrets Manager entries. NO secret VALUES
 * appear here — db-password is generated by Secrets Manager; the rest are empty
 * placeholders populated out-of-band before the first deploy (see README). ECS
 * task definitions reference these ARNs via `secrets:` (valueFrom), so the
 * plaintext never lands in CloudFormation, task defs, or images.
 */
export class SecretsStack extends cdk.Stack {
  public readonly jwtSecret: secretsmanager.Secret;
  public readonly dbPassword: secretsmanager.Secret;
  public readonly twilioAuthToken: secretsmanager.Secret;
  public readonly anthropicApiKey: secretsmanager.Secret;
  public readonly slackWebhookUrl: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Generated on create — value never materialises in source or templates.
    this.jwtSecret = new secretsmanager.Secret(this, 'JwtSecret', {
      secretName: 'scheduler/prod/jwt-secret',
      description: 'HS256 signing key for API JWTs (>= 256-bit).',
      generateSecretString: {
        passwordLength: 48,
        excludePunctuation: true,
      },
    });

    this.dbPassword = new secretsmanager.Secret(this, 'DbPassword', {
      secretName: 'scheduler/prod/db-password',
      description: 'RDS PostgreSQL master password.',
      generateSecretString: {
        passwordLength: 32,
        excludePunctuation: true,
      },
    });

    // External-provider credentials — created empty, filled via CLI (README).
    this.twilioAuthToken = new secretsmanager.Secret(this, 'TwilioAuthToken', {
      secretName: 'scheduler/prod/twilio-auth-token',
      description: 'Twilio auth token (SMS OTP dispatch). Populate out-of-band.',
    });

    this.anthropicApiKey = new secretsmanager.Secret(this, 'AnthropicApiKey', {
      secretName: 'scheduler/prod/anthropic-api-key',
      description: 'Anthropic API key (AI slot optimization). Populate out-of-band.',
    });

    this.slackWebhookUrl = new secretsmanager.Secret(this, 'SlackWebhookUrl', {
      secretName: 'scheduler/prod/slack-webhook-url',
      description: 'Alertmanager Slack incoming-webhook URL. Populate out-of-band.',
    });

    new cdk.CfnOutput(this, 'JwtSecretArn', { value: this.jwtSecret.secretArn });
    new cdk.CfnOutput(this, 'DbPasswordArn', { value: this.dbPassword.secretArn });
  }
}
